#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { CATEGORY_IDS } from "@omnio/core";
import { createFsContext, discoverModuleSources, findRepoRoot } from "./discover.js";
import { generateRegistries } from "./generate.js";
import { validateModules } from "./validate.js";

const MODULE_PACKAGE_PREFIX = "@omnio/mod-";

function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return false;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  return true;
}

interface PackageJson {
  dependencies?: Record<string, string>;
  [key: string]: unknown;
}

/** Keep an app's @omnio/mod-* deps exactly matching the modules it consumes. */
function syncModuleDeps(pkgPath: string, needed: string[]): boolean {
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as PackageJson;
  const deps = pkg.dependencies ?? {};
  const kept: Record<string, string> = {};
  for (const [name, version] of Object.entries(deps)) {
    if (!name.startsWith(MODULE_PACKAGE_PREFIX)) kept[name] = version;
  }
  for (const name of [...needed].sort()) kept[name] = "workspace:*";
  pkg.dependencies = kept;
  const next = `${JSON.stringify(pkg, null, 2)}\n`;
  return writeIfChanged(pkgPath, next);
}

export function run(repoRoot: string): void {
  const modulesRoot = join(repoRoot, "packages", "modules");
  const sources = discoverModuleSources(modulesRoot);
  const ctx = createFsContext(modulesRoot, CATEGORY_IDS);
  const { modules, errors } = validateModules(sources, ctx);

  if (errors.length > 0) {
    process.stderr.write(`\nmodgen: ${errors.length} manifest problem(s):\n`);
    for (const error of errors) {
      process.stderr.write(`  ✖ [${error.module}] ${error.message}\n`);
    }
    process.stderr.write("\nFix the manifests above and re-run. Nothing was generated.\n");
    process.exit(1);
  }

  const registries = generateRegistries(modules);

  const webGen = join(repoRoot, "apps", "web", "src", "generated");
  const apiGen = join(repoRoot, "apps", "api", "src", "generated");
  const workerGen = join(repoRoot, "apps", "worker", "src", "generated");

  writeIfChanged(join(webGen, "registry.search.ts"), registries.searchTs);
  writeIfChanged(join(webGen, "registry.web.ts"), registries.webTs);
  writeIfChanged(join(webGen, "messages.ts"), registries.messagesTs);
  writeIfChanged(join(webGen, "capabilities.json"), registries.capabilitiesJson);
  writeIfChanged(
    join(webGen, "modules.ts"),
    `// AUTO-GENERATED by @omnio/modgen — do not edit by hand.\nexport const MODULE_PACKAGES = ${JSON.stringify(
      registries.modulePackages,
    )} as const;\n`,
  );
  writeIfChanged(join(apiGen, "registry.api.ts"), registries.apiTs);
  writeIfChanged(join(workerGen, "registry.worker.ts"), registries.workerTs);

  const webPkgs = modules.map((m) => `${MODULE_PACKAGE_PREFIX}${m.manifest.id}`);
  const apiPkgs = modules
    .filter((m) => m.manifest.tools.some((t) => t.tier === "server"))
    .map((m) => `${MODULE_PACKAGE_PREFIX}${m.manifest.id}`);
  const workerPkgs = modules
    .filter((m) => m.manifest.tools.some((t) => t.tier === "worker"))
    .map((m) => `${MODULE_PACKAGE_PREFIX}${m.manifest.id}`);

  syncModuleDeps(join(repoRoot, "apps", "web", "package.json"), webPkgs);
  syncModuleDeps(join(repoRoot, "apps", "api", "package.json"), apiPkgs);
  syncModuleDeps(join(repoRoot, "apps", "worker", "package.json"), workerPkgs);

  process.stdout.write(
    `modgen: ${modules.length} module(s), ${registries.modulePackages.length} package(s) wired.\n`,
  );
}

run(findRepoRoot(process.cwd()));
