import type { ModuleManifest } from "@omnio/module-sdk";
import type { LoadedModule } from "./validate";

const HEADER = `// AUTO-GENERATED by @omnio/modgen — do not edit by hand.
// Run \`pnpm modgen\` to regenerate after changing a module manifest.
`;

export interface GeneratedRegistries {
  searchTs: string;
  webTs: string;
  messagesTs: string;
  apiTs: string;
  workerTs: string;
  capabilitiesJson: string;
  /** Module package names for Next transpilePackages. */
  modulePackages: string[];
}

const pkg = (id: string): string => `@omnio/mod-${id}`;
const key = (moduleId: string, toolId: string): string => `${moduleId}.${toolId}`;
const ident = (value: string): string => value.replace(/[^a-zA-Z0-9]/g, "_");
const sortById = (modules: LoadedModule[]): LoadedModule[] =>
  [...modules].sort((a, b) => a.manifest.id.localeCompare(b.manifest.id));

interface FlatTool {
  moduleId: string;
  manifest: ModuleManifest;
  toolId: string;
  tier: "browser" | "server" | "worker";
  surface: string;
  category: string;
  icon: string;
  i18nNamespace: string;
  keywords: string[];
}

function flattenTools(modules: LoadedModule[]): FlatTool[] {
  const tools: FlatTool[] = [];
  for (const { manifest } of sortById(modules)) {
    for (const tool of manifest.tools) {
      tools.push({
        moduleId: manifest.id,
        manifest,
        toolId: tool.id,
        tier: tool.tier,
        surface: tool.surface,
        category: manifest.category,
        icon: manifest.icon,
        i18nNamespace: manifest.i18nNamespace,
        keywords: tool.keywords ?? [],
      });
    }
  }
  return tools;
}

function generateSearch(tools: FlatTool[]): string {
  const entries = tools
    .map((tool) =>
      [
        "  {",
        `    id: ${JSON.stringify(key(tool.moduleId, tool.toolId))},`,
        `    moduleId: ${JSON.stringify(tool.moduleId)},`,
        `    toolId: ${JSON.stringify(tool.toolId)},`,
        `    tier: ${JSON.stringify(tool.tier)},`,
        `    category: ${JSON.stringify(tool.category)},`,
        `    icon: ${JSON.stringify(tool.icon)},`,
        `    i18nNamespace: ${JSON.stringify(tool.i18nNamespace)},`,
        `    nameKey: ${JSON.stringify(`tools.${tool.toolId}.name`)},`,
        `    descriptionKey: ${JSON.stringify(`tools.${tool.toolId}.description`)},`,
        `    keywords: ${JSON.stringify(tool.keywords)},`,
        `    href: ${JSON.stringify(`/tool/${tool.moduleId}/${tool.toolId}`)},`,
        "  },",
      ].join("\n"),
    )
    .join("\n");
  return `${HEADER}
export interface SearchEntry {
  id: string;
  moduleId: string;
  toolId: string;
  tier: "browser" | "server" | "worker";
  category: string;
  icon: string;
  i18nNamespace: string;
  nameKey: string;
  descriptionKey: string;
  keywords: string[];
  href: string;
}

export const SEARCH_ENTRIES: SearchEntry[] = [
${entries}
];
`;
}

function generateWeb(tools: FlatTool[]): string {
  const imports = tools
    .map(
      (tool) =>
        `  ${JSON.stringify(key(tool.moduleId, tool.toolId))}: dynamic(() => import(${JSON.stringify(
          `${pkg(tool.moduleId)}/${tool.surface}`,
        )})),`,
    )
    .join("\n");
  const meta = tools
    .map(
      (tool) =>
        `  ${JSON.stringify(key(tool.moduleId, tool.toolId))}: { moduleId: ${JSON.stringify(
          tool.moduleId,
        )}, toolId: ${JSON.stringify(tool.toolId)}, tier: ${JSON.stringify(
          tool.tier,
        )}, category: ${JSON.stringify(tool.category)}, icon: ${JSON.stringify(
          tool.icon,
        )}, i18nNamespace: ${JSON.stringify(tool.i18nNamespace)} },`,
    )
    .join("\n");
  return `${HEADER}
import dynamic from "next/dynamic";
import type { ComponentType } from "react";

export const TOOL_SURFACES: Record<string, ComponentType> = {
${imports}
};

export interface WebToolMeta {
  moduleId: string;
  toolId: string;
  tier: "browser" | "server" | "worker";
  category: string;
  icon: string;
  i18nNamespace: string;
}

export const WEB_TOOLS: Record<string, WebToolMeta> = {
${meta}
};
`;
}

function generateApi(modules: LoadedModule[]): string {
  const serverModules = sortById(modules).filter((m) =>
    m.manifest.tools.some((t) => t.tier === "server"),
  );
  if (serverModules.length === 0) {
    return `${HEADER}
export const API_MODULES: never[] = [];
`;
  }
  const imports = serverModules
    .map(
      (m) =>
        `import Mod_${ident(m.manifest.id)} from ${JSON.stringify(`${pkg(m.manifest.id)}/server`)};`,
    )
    .join("\n");
  const list = serverModules.map((m) => `  Mod_${ident(m.manifest.id)},`).join("\n");
  return `${HEADER}
import type { DynamicModule, Type } from "@nestjs/common";
${imports}

export const API_MODULES: Array<Type<unknown> | DynamicModule> = [
${list}
];
`;
}

function generateWorker(tools: FlatTool[]): string {
  const workerTools = tools.filter((t) => t.tier === "worker");
  if (workerTools.length === 0) {
    // No worker tools yet — emit a self-contained empty map so the worker app
    // needs no @omnio/module-sdk dependency until it actually has processors.
    return `${HEADER}
export const WORKER_TOOLS: Record<string, never> = {};
`;
  }
  const imports = workerTools
    .map(
      (tool) =>
        `import ${ident(key(tool.moduleId, tool.toolId))} from ${JSON.stringify(
          `${pkg(tool.moduleId)}/worker/tools/${tool.toolId}`,
        )};`,
    )
    .join("\n");
  const map = workerTools
    .map(
      (tool) =>
        `  ${JSON.stringify(key(tool.moduleId, tool.toolId))}: ${ident(key(tool.moduleId, tool.toolId))},`,
    )
    .join("\n");
  return `${HEADER}
import type { WorkerTool } from "@omnio/module-sdk";
${imports}

export const WORKER_TOOLS: Record<string, WorkerTool<unknown>> = {
${map}
};
`;
}

interface CapabilityEntry {
  moduleId: string;
  toolId: string;
  verb: string;
  rank: number;
}

function generateCapabilities(modules: LoadedModule[]): string {
  const byMime: Record<string, CapabilityEntry[]> = {};
  for (const { manifest } of sortById(modules)) {
    const actions = manifest.capabilities?.fileActions ?? [];
    for (const action of actions) {
      const tool = manifest.tools.find((t) => t.id === action.toolId);
      const mimes = tool?.accepts?.flatMap((a) => a.mime) ?? [];
      for (const mime of mimes) {
        (byMime[mime] ??= []).push({
          moduleId: manifest.id,
          toolId: action.toolId,
          verb: action.verb,
          rank: action.rank,
        });
      }
    }
  }
  for (const list of Object.values(byMime)) {
    list.sort((a, b) => b.rank - a.rank);
  }
  return `${JSON.stringify({ byMime }, null, 2)}\n`;
}

function generateMessages(modules: LoadedModule[]): string {
  const sorted = sortById(modules);
  const imports = sorted
    .map(
      (m) =>
        `import ${ident(m.manifest.id)}_en from ${JSON.stringify(`${pkg(m.manifest.id)}/i18n/en`)};\n` +
        `import ${ident(m.manifest.id)}_he from ${JSON.stringify(`${pkg(m.manifest.id)}/i18n/he`)};`,
    )
    .join("\n");
  const line = (m: LoadedModule, locale: "en" | "he"): string =>
    `    ${JSON.stringify(m.manifest.i18nNamespace)}: ${ident(m.manifest.id)}_${locale},`;
  const en = sorted.map((m) => line(m, "en")).join("\n");
  const he = sorted.map((m) => line(m, "he")).join("\n");
  return `${HEADER}
${imports}

/** Per-module catalogs merged into the app messages under their namespace. */
export const MODULE_MESSAGES = {
  en: {
${en}
  },
  he: {
${he}
  },
} as const;

export type ModuleMessages = (typeof MODULE_MESSAGES)["en"];
`;
}

export function generateRegistries(modules: LoadedModule[]): GeneratedRegistries {
  const tools = flattenTools(modules);
  return {
    searchTs: generateSearch(tools),
    webTs: generateWeb(tools),
    messagesTs: generateMessages(modules),
    apiTs: generateApi(modules),
    workerTs: generateWorker(tools),
    capabilitiesJson: generateCapabilities(modules),
    modulePackages: sortById(modules).map((m) => pkg(m.manifest.id)),
  };
}
